version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.2008r2
    ports:
      - "8000:8000"
    working_dir: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.2008r2
    ports:
      - "3000:3000"
    volumes:
      - /home/mitmas/docker/uploads:/app/uploads
    working_dir: /app