version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.2008r2
    ports:
      - "8080:8080"
    working_dir: /app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.2008r2
    ports:
      - "3000:3000"
    working_dir: /app